manifest = "118fa3b77ecc4f968094a5cfd8f68e9e199c8f16c3d2ba6fe93397a77ec295e4"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.67.0" ]
revision = "d33f5202a6d3d8e42cccd641c8d78e7b467fec8d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.67.0" ]
revision = "5782f108397199eccd4404780d37513b42798a43"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.67.0" ]
revision = "205cacd6bff72f09635287926d379c56ec87899d"
