manifest = "1d2d2004929986507986f325fc73c3c0781d703df52f40d7146a7ea82ad12181"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.62.0" ]
revision = "484f0f9359c0896a0ea9ae1f471c4586b2bb1591"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.62.0" ]
revision = "aabf1b51ad20471ec869ae8db30d4f8da170e6a2"
