manifest = "9c344a92c83fb7b3414dfffaeb4b5876c20f693687bce8dcc80b0c18921ea6c0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.63.0" ]
revision = "9b56785b10414925c36e556e091726b7bd8611c3"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.63.0" ]
revision = "f4f11472a3df6451547ae5c1023434485590e80e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.63.0" ]
revision = "8a7a59a2eae5811359811bb944e09a50f29cf363"
