manifest = "3a5bead40a27a317efba6d107521b9ea1e692caa480e9f851b3cca19d1a064d4"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.49.0" ]
revision = "d3a4298d018723c63cbecab085f0aa8a6e2e6211"
