manifest = "df552a6466d4513ee54ff380fd61594adf5ee6505c42cc725f95b1b9a8deb1c7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.0" ]
revision = "d464187703a522223f9f3b01b4fbe8f8ae05fad6"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.0" ]
revision = "7268ab966b715d5702f1a2b98990626f1c193e6f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.0" ]
revision = "296264e87d794813a2c6681e56ca783560d4961d"
